# Generated by Django 6.0.6 on 2026-06-21 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('domaine', models.CharField(blank=True, max_length=150)),
                ('transversale', models.BooleanField(default=False, help_text='Matière transversale (maths, anglais, méthodologie...) : le matching reste possible même entre domaines éloignés.')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
            ],
            options={
                'verbose_name': 'Disponibilité',
                'verbose_name_plural': 'Disponibilités',
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_annonce', models.CharField(choices=[('offre', "J'offre du mentorat"), ('demande', "Je recherche de l'aide")], max_length=10)),
                ('domaine_etudes', models.CharField(max_length=150)),
                ('niveau', models.CharField(choices=[('licence', 'Licence (L1-L3)'), ('master', 'Master (M1-M2)'), ('autre', 'Autre')], default='licence', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL)),
                ('competences', models.ManyToManyField(related_name='annonces', to='matching.competence')),
                ('disponibilites', models.ManyToManyField(blank=True, related_name='annonces', to='matching.disponibilite')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='Score de compatibilité sur 100')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annonce_demande', models.ForeignKey(limit_choices_to={'type_annonce': 'demande'}, on_delete=django.db.models.deletion.CASCADE, related_name='matches_demande', to='matching.annonce')),
                ('annonce_offre', models.ForeignKey(limit_choices_to={'type_annonce': 'offre'}, on_delete=django.db.models.deletion.CASCADE, related_name='matches_offre', to='matching.annonce')),
                ('competences_communes', models.ManyToManyField(blank=True, related_name='matches', to='matching.competence')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['-score'],
                'unique_together': {('annonce_offre', 'annonce_demande')},
            },
        ),
    ]
